// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import CommandPaletteController from "./command_palette_controller"
application.register("command-palette", CommandPaletteController)

import DropdownController from "./dropdown_controller"
application.register("dropdown", DropdownController)

import EditableController from "./editable_controller"
application.register("editable", EditableController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import PasswordVisibilityController from "./password_visibility_controller"
application.register("password-visibility", PasswordVisibilityController)

import SelectSkillController from "./select_skill_controller"
application.register("select-skill", SelectSkillController)

import SelectTagController from "./select_tag_controller"
application.register("select-tag", SelectTagController)

import SetPrivateController from "./set_private_controller"
application.register("set-private", SetPrivateController)

import Timeago from "stimulus-timeago"
application.register('timeago', Timeago)

import StimulusTimeagoController from "./stimulus_timeago_controller"
application.register("stimulus-timeago", StimulusTimeagoController)

import TiptapController from "./tiptap_controller"
application.register("tiptap", TiptapController)
